language: python
python:
  - "3.8-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - ls
  - python3 src/pur_beurre/manage.py test
addons:
  chrome: stable
